### ISSUE TITLE
Hyperlink in APA cites

### ISSUE THREAD

**Issue by demberjavier** [mabentwickeltsich/MendeleyMacros#10]
Hi, so I start using this macro and it's good for my works.
When I use the macro to create hyperlinks for my references URLs, it happens this:
The macro hyperlinks the cites when they don't have a URL in the References list. In "Besterfield" as this text doesn't have a URL in the reference list it hyperlinks the cite.
I wonder why this happens and if there is a way to fix this. Thanks :D
![image](https://user-images.githubusercontent.com/67807901/86499135-0c05e380-bd4f-11ea-919d-4649bc535ccb.png)

**Comment by mabentwickeltsich** [comment]
Dear @demberjavier,

I am not sure if it is the URL that causes problems. It may be that you do not have a year in GeoGebra and that you have the month in Wyngaard.
Try changing those entries adding a year and removing the month and see what happens.

Cheers
Luis

**Comment by mabentwickeltsich** [comment]
The new _Quick start guides_ available on YouTube describe how to handle orphan citations.

**Comment by mabentwickeltsich** [comment]
The new _Quick start guides_ available on YouTube describe how to handle orphan citations.
