### ISSUE TITLE
Macro executed but no hyperlinks created

### ISSUE THREAD

**Issue by franklinliot** [mabentwickeltsich/MendeleyMacros#13]
Hello,

I tried entering the _GAUG_createHyperlinksForCitationsAPA()_ Macro but when I run it, it doesn't seem to create the hyperlinks. I put you a screenshot of the code I entered. 
![Capture](https://user-images.githubusercontent.com/82656739/115222025-94048080-a10a-11eb-9431-86ddc7c25e64.JPG).

Is it because of the "refreshdocument" macro I need to edit? Because I tried to access it but Word states that the project is unviewable.

(I use APA)

Best,

**Comment by charlesweir** [comment]
Doesn't look like you have the whole of the subroutine in there! Suggest trying again.

**Comment by mabentwickeltsich** [comment]
Thanks @charlesweir for the hint.

Dear @franklinliot,

I am sorry for this late (and perhaps useless) reply. I have not been able to check the status of the repository with regularity. As @charlesweir pointed out, you have just copied the header of the macro and the juicy part is missing. Follow the instructions again to install the macros and make sure you copy the full code of each macro.

Cheers

**Comment by Nangu2004** [comment]
It did not work for me, kindly help and what could be the problem? 
![IT DID NOT WORK ](https://github.com/mabentwickeltsich/MendeleyMacros/assets/175323958/5d509abc-a5ce-40ea-9701-1af50b7588f5)

**Comment by mabentwickeltsich** [comment]
Dear @Nangu2004, I cannot see what user-defined type is the error about in the image.
I have not been able to work on the code recently. However, it seems that the new versions of Mendeley create the references in a different way and the macros do not work correctly. This is based on the comments by others. I would recommend to use an older version of Mendeley and try again.
Cheers

**Comment by mabentwickeltsich** [comment]
Dear @Nangu2004, I have done some tests in a fresh installation. Using Mendeley Desktop 1.19.8 and MS Word 2019, the error that you have is most likely due to the missing RegExp object. You need to activate regular expressions in MS Word. Follow the instructions and try again.

Cheers

**Comment by mabentwickeltsich** [comment]
The new release of Mendeley Macros uses _Late binding_, which prevents this error. It is not necessary to activate the RegExp object (the library _Microsoft VBScript Regular Expressions 5.5_) anymore.
