### ISSUE TITLE
Hyperlins created but doesn´t correspond to the bookmark

### ISSUE THREAD

**Issue by bladitoaza** [mabentwickeltsich/MendeleyMacros#17]
When I use GAUG_createHyperlinksForCitationsAPA() it creates the hyperlink but it doesn´t corresponde to the bookmark.
![screenshot](https://user-images.githubusercontent.com/73363588/200708791-1dd0683a-863c-4f7a-970d-87833efe9ef3.png)
![screenshot1](https://user-images.githubusercontent.com/73363588/200708795-631cae1c-f3cc-4046-a9fe-2ee1b9e3879f.png)

All the hyperlinks are incorrect

**Comment by mabentwickeltsich** [comment]
@bladitoaza,

there is a new release of Mendeley Macros with new features and improvements. This issue may have been resolved already.

Cheers
