### ISSUE TITLE
String parameter too long.

### ISSUE THREAD

**Issue by moedwyn** [mabentwickeltsich/MendeleyMacros#18]
Thank you for creating such a useful macro. but I encountered an error when the url was too long. This can be solved by modifying the URL, but sometimes the bibliography URL has to be long. I request that improvements be made to this section. thank you very much.

Run-time error '5854':
String parameter too long.
pada 
.text = strURL

in the block of

                                    'finds and selects the text of the URL
                                    With Selection.Find
                                        .Forward = True
                                        .Wrap = wdFindStop
                                        .text = strURL
                                        .Execute
                                        blnURLFound = .found
                                    End With

**Comment by moedwyn** [comment]
I found the solution by adding the ccut url function before the block to find selects the text. However, this makes the related libbiography imperfect.

```
                                    ' Cut URL
                                    If Len(strURL) > 255 Then
                                        Debug.Print "Referensi #" & debugCounter & " memiliki URL terlalu panjang:"
                                        Debug.Print "URL: " & strURL
                                        Debug.Print "Panjang: " & Len(strURL) & " karakter"
                                        Debug.Print "---"
                                        
                                        strURL = Left(strURL, 255)
                                        debugCounter = debugCounter + 1
                                    End If
```

**Comment by mabentwickeltsich** [comment]
Dear @frijheid,

thank you for the feedback; I did not considered this scenario in the past. The new release of Mendeley Macros has new features and a fix for this problem.

Cheers
