### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by samuelduchesne** [mabentwickeltsich/MendeleyMacros#2]
This set of macros allows me the format the citation numbers in the text in another colour (through changing the "Hyperlink" character style in Word). My only concern is that it doesn't affect the brackets flanking the IEEE reference numbers; the brackets themselves don't change colour. How could this be achieved? The idea is to mimic the format of any scientific journal papers hosted by Elsevier. Thanks!

**Comment by mabentwickeltsich** [comment]
Hey @samuelduchesne 

Have a look at commit [aa3c02d](https://github.com/mabentwickeltsich/MendeleyMacros/commit/aa3c02d2d2754264d8e6010e58c0ee78cc83269d) when I added code to EXCLUDE the brackets. Remove or comment the code and you will have the brackets with the same format as the citation numbers.

Perhaps a good idea to set this as parameter to allow people to choose?

Cheers
Luis

**Comment by samuelduchesne** [comment]
Thanks! Yes, I guess users would love it. Or just mention it in the description?

Sam

**Comment by mabentwickeltsich** [comment]
There is a new version of the macros allowing the user to choose if the square brackets will be part of the hyperlinks (IEEE CSL citation style). However, Microsoft Word produces errors while removing the hyperlinks with the normal procedure. The parameter `strTypeOfExecution` CANNOT have the value `"RemoveHyperlinks"` if the square brackets are part of the hyperlinks. You can still remove them with the other two values for the parameter.
